get:
  operationId: get_space_auto_cleaning_configuration
  summary: Get space auto-cleaning configuration
  description: >
    Returns configuration of auto-cleaning mechanism in the space specified by space Id in the path.
  x-onedata-gri:
    type: onp_space
    id: ?BINDING(id)
    aspect: auto_cleaning_configuration
  tags:
    - File popularity and Auto-cleaning
  produces:
    - application/json
  responses:
    '200':
      description: The space auto-cleaning configuration.
      schema:
        $ref: '#/definitions/SpaceAutoCleaningConfiguration'
    '401':
      description: Unauthorized request.
    '403':
      description: Forbidden request.
    '404':
      description: Space does not exist or is not supported by the provider.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: id
    in: path
    type: string
    description: The Id of a space of which auto-cleaning configuration should be returned.
    required: true
  x-code-samples:
  - lang: Shell
    source: onepanel-rest-cli -u onepanel:$PASSPHRASE getSpaceAutoCleaningConfiguration id=$SPACE_ID --host https://$HOST:9443

patch:
  operationId: configure_space_auto_cleaning
  summary: Configure space auto-cleaning mechanism
  description: >
    Configures space auto-cleaning mechanism in the space.
  x-onedata-gri:
    type: onp_space
    id: ?BINDING(id)
    aspect: auto_cleaning_configuration
  tags:
    - File popularity and Auto-cleaning
  produces:
    - application/json
  responses:
    '204':
      description: Auto-cleaning configuration has been updated.
    '401':
      description: Unauthorized request.
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
    - name: id
      in: path
      type: string
      description: The Id of a space.
      required: true
    - name: spaceAutoCleaningConfiguration
      in: body
      description: >
        New configuration of space auto-cleaning mechanism.
      schema:
        $ref: '#/definitions/SpaceAutoCleaningConfiguration'
      required: true
  x-code-samples:
    - lang: Shell
      source: >
        cat new_auto_cleaning_config.json | onepanel-rest-cli -u onepanel:$PASSPHRASE --host https://$HOST:9443
        configureSpaceAutoCleaning id=$SPACE_ID -
