get:
  operationId: get_configuration
  summary: Get public configuration
  description: Returns public configuration details.
  x-onedata-gri:
    type: onp_panel
    aspect: configuration
  tags:
    - Cluster
  produces:
    - application/json
  responses:
    '200':
      description: Configuration details.
      schema:
        $ref: '#/definitions/Configuration'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
