get:
  operationId: get_configuration
  summary: Get public configuration
  description: Returns public configuration information.
  x-onedata-version: 3
  x-onedata-module: rest_onepanel
  x-onedata-resource: configuration
  x-onedata-noauth: true
  tags:
    - Onepanel
  produces:
    - application/json
  responses:
    '200':
      description: The configuration info.
      schema:
        $ref: '#/definitions/Configuration'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
