get:
  operationId: get_dns_check_configuration
  summary: Return settings used when performing the DNS check.
  description: >
    Returns servers queried to check DNS configuration correctness.
  x-onedata-gri:
    type: onp_panel
    aspect: dns_check_configuration
  tags:
    - Onepanel
  produces:
    - application/json
  responses:
    '200':
      description: The DNS check results.
      schema:
        $ref: '#/definitions/DnsCheckConfiguration'
    '401':
      description: Unauthorized request.
    '403':
      description: Forbidden request.
    '404':
      description: Cluster not yet deployed.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  x-code-samples:
  - lang: Shell
    source: onepanel-rest-cli -u onepanel:$PASSPHRASE getDnsCheckConfiguration --host https://$HOST:9443

patch:
  operationId: modify_dns_check_configuration
  summary: Configure dns check
  description: >
    Informs what DNS servers to use for checking external DNS records validity.
  x-onedata-gri:
    type: onp_panel
    aspect: dns_check_configuration
  tags:
    - Onepanel
  consumes:
    - application/json
    - application/x-yaml
  responses:
    '204':
      description: Changes successfully saved.
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: dnsCheckConfiguration
    in: body
    description: The configuration changes.
    schema:
      $ref: '#/definitions/DnsCheckConfiguration'
    required: true
  x-code-samples:
  - lang: Shell
    source: >
      echo '{"dnsServers": ["8.8.8.8", "8.8.4.4"]}' |
      onepanel-rest-cli -u onepanel:$PASSPHRASE modifyDnsCheckConfiguration --host https://$HOST:9443

