get:
  operationId: get_cluster_hosts
  summary: Get cluster hosts
  description: >
    Returns the list of administrative cluster hosts.
  x-onedata-gri:
    type: onp_host
    aspect: list
  tags:
    - Cluster
  produces:
    - application/json
  responses:
    '200':
      description: The list of administrative cluster hosts.
      schema:
        type: array
        description: List of cluster hosts.
        items:
          type: string
        example:
          - host1.example.org
          - host2.example.org
          - host3.example.org
    '401':
      description: Unauthorized request.
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  x-code-samples:
    - lang: Shell
      source: onepanel-rest-cli -u onepanel:$PASSPHRASE getClusterHosts --host https://$HOST:9443


post:
  operationId: add_cluster_host
  summary: Add given host to the cluster
  description: >
    Adds given host to the current cluster. The host can be specified
    by any address by which it is reachable.
    Upon success returns proper hostname used to address the new host in cluster
    management.
  x-onedata-gri:
    type: onp_host
    aspect: instance
  tags:
    - Cluster
  consumes:
    - application/json
  responses:
    '200':
      description: Host added.
      schema:
        $ref: '#/definitions/Host'
    '401':
      description: Unauthorized request.
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
    - name: HostAddRequest
      in: body
      schema:
        $ref: '#/definitions/HostAddRequest'
      required: true
  x-code-samples:
    - lang: Shell
      source: onepanel-rest-cli -u onepanel:$PASSPHRASE addClusterHost address==$HOSTNAME --host https://$HOST:9443
