swagger: '2.0'
basePath: /api/v3/onepanel
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Onepanel
    description: Common Onepanel resources and operations
  - name: Oneprovider
    description: Resources and operations for managing Oneprovider deployment
  - name: Onezone
    description: Resources and operations for managing Onezone deployment
securityDefinitions:
  basic:
    type: basic
  api_key1:
    type: apiKey
    name: Authorization  # Header value must start with "Bearer "
    in: header
  api_key2:
    type: apiKey
    name: X-Auth-Token
    in: header
security:
  - basic: []
  - api_key1: []
  - api_key2: []
  # NOTE: The last key on this list is used by REST-CLI generator as 
  # default authentication method, make sure it's X-Auth-Token
