swagger: '2.0'
basePath: /api/v3/onepanel
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
responses:
  $ref: ./responses/index.yaml
tags:
  - name: Cluster
    description: Endpoints for cluster management.
  - name: Security
    description: Endpoints related to security.
  - name: DNS
    description: Tools for DNS diagnostics.
  - name: Current User
    description: Endpoints for serving information about the currently authenticated user.
  - name: Internal
    description: Endpoints used internally by Onedata components.
  - name: Onezone Cluster
    description: Endpoints for managing Onezone cluster and underlying services.
  - name: Service Configuration
    description: Endpoints for configuring the Onezone service.
  - name: User Management
    description: Endpoints for managing users in Onezone.
  - name: Oneprovider Cluster
    description: Endpoints for managing Oneprovider cluster and services.
  - name: Oneprovider Identity
    description: Endpoints for Oneprovider registration and identity management.
  - name: Storages
    description: Endpoints for managing storages.
  - name: Storage Import
    description: Endpoints for storage import management.
  - name: Space Support
    description: Endpoints for space support management.
  - name: LUMA DB
    description: Endpoints for LUMA DB for the specific storage resource management.
  - name: LUMA DB Local Feed
    description: >
      Endpoints for managing local feed of LUMA DB for the specific storage resource.
      All operations in this group return error if the storage has a different LUMA feed than `local`.
  - name: File Popularity
    description: Endpoints for managing the file popularity mechanisms.
  - name: Auto Cleaning
    description: Endpoints for managing the auto-cleaning mechanisms.
  - name: Ceph
    description: Endpoints for managing the embedded Ceph cluster.
  - name: Debug
    description: Endpoints for debugging purposes.
x-tagGroups:
  - name: ONEPANEL COMMON
    tags:
      - Cluster
      - Security
      - DNS
      - Current User
      - Internal
  - name: ONEZONE ADMINISTRATION
    tags:
      - Onezone Cluster
      - Service Configuration
      - User Management
  - name: ONEPROVIDER ADMINISTRATION
    tags:
      - Oneprovider Cluster
      - Oneprovider Identity
      - Storages
      - Space Support
      - Storage Import
      - LUMA DB
      - LUMA DB Local Feed
      - File Popularity
      - Auto Cleaning
      - Ceph
      - Debug
securityDefinitions:
  # api_key1 is used by Bash generated clients as default
  # header for sending api key
  basic:
    type: basic
  api_key1:
    type: apiKey
    name: X-Auth-Token
    in: header
  api_key2:
    type: apiKey
    # When using this method, the token must be prefixed with 'Bearer '
    name: Authorization
    in: header
security:
  - basic: []
  - api_key1: []
  - api_key2: []
