swagger: '2.0'
basePath: /api/v3/onepanel
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
responses:
  $ref: ./responses/index.yaml
tags:
  - name: Onepanel
    description: Common Onepanel resources and operations
  - name: Oneprovider
    description: Resources and operations for managing Oneprovider deployment
  - name: Onezone
    description: Resources and operations for managing Onezone deployment
x-tagGroups:
  - name: Onepanel
    tags:
      - Onepanel
  - name: Onezone
    tags:
      - Onezone
  - name: Oneprovider
    tags:
      - Oneprovider
      - LUMA
securityDefinitions:
  # api_key1 is used by Bash generated clients as default
  # header for sending api key
  basic:
    type: basic
  api_key1:
    type: apiKey
    name: X-Auth-Token
    in: header
  api_key2:
    type: apiKey
    # When using this method, the token must be prefixed with 'Bearer '
    name: Authorization
    in: header
security:
  - basic: []
  - api_key1: []
  - api_key2: []
