#!/usr/bin/env bash

ARTEFACT=onepanel-swagger.documentation.onedata.org.tar
FILE_TO_SHIP=dockerimage.sha
if [ -f $FILE_TO_SHIP ]; then
    tar cvf $ARTEFACT --exclude .git  --exclude "$ARTEFACT" $FILE_TO_SHIP
else
    echo "No $FILE_TO_SHIP found in the current directory." 
fi 
