type: object
description: >
  Configuration of auto storage import mechanism.
  The auto import is based on scans - gradual traversing of the file system and
  registration of files and directories.
properties:
  maxDepth:
    type: integer
    description: >
      Maximum depth of filesystem tree that will be traversed during the scan.
    default: 65535
  syncAcl:
    type: boolean
    description: >
      Flag that enables synchronization of NFSv4 ACLs.
    default: false
  continuousScan:
    description: >
      With this option enabled the storage will be scanned periodically and direct changes on the
      storage will be reflected in the assigned Onedata space (upon the consecutive scan).
    type: boolean
    default: false
  scanInterval:
    type: integer
    description: >
      Period between subsequent scans in seconds (counted from end of one scan
      till beginning of the following). This parameter is relevant only for continuous scans.
    default: 60
  detectModifications:
    type: boolean
    description: >
      Flag determining that modifications of files on the synchronized storage will be detected.
      If disabled, the storage will be treated as immutable
      (only creations and deletions of files on storage will be detected).
      This parameter is relevant only for continuous scans.
    default: true
  detectDeletions:
    type: boolean
    description: >
      Flag determining that deletions of files from the synchronized storage will be detected.
      This parameter is relevant only for continuous scans.
    default: true