type: object
description: The cluster configuration.
properties:
  master:
    type: string
    description: Host responsible for deploying cluster and coordinating cluster restarts.
  hosts:
    type: array
    description: List of hosts belonging to the Onepanel cluster.
    items:
      type: string
  databases:
    $ref: '#/definitions/DatabaseHosts'
  managers:
    $ref: '#/definitions/ManagerHosts'
  workers:
    $ref: '#/definitions/WorkerHosts'
required:
  - master
  - hosts
  - databases
  - managers
  - workers
