type: object
description: Public service configuration details
discriminator: serviceType
x-onedata-oneof: true
x-onedata-subclasses:
  - op_configuration
  - oz_configuration
properties:
  clusterId:
    type: string
    description: The Id of cluster recod for this cluster.
      Null if the cluster is not registered or worker is offline.
  version:
    type: string
    description: Version of this Onepanel
  build:
    type: string
    description: Build number of this Onepanel
  deployed:
    type: boolean
    default: true
    description: True when cluster deployment is finished
required:
  - clusterId
  - version
  - build
  - deployed
