type: object
description: Public configuration information.
discriminator: serviceType
x-onedata-oneof: true
x-onedata-subclasses:
  - OpConfiguration
  - OzConfiguration
properties:
  version:
    type: string
    description: Version of this Onepanel
  build:
    type: string
    description: Build number of this Onepanel
  deployed:
    type: boolean
    default: true
    description: True when initial cluster deployment is finished
required:
  - version
  - build
  - deployed
