type: object
description: Public Oneprovider configuration details.
allOf:
  - $ref: '#/definitions/Configuration'
  - type: object
    properties:
      serviceType:
        description: Indicates that this is Oneprovider's panel.
        type: string
        enum: [oneprovider]
        x-discriminator-value: oneprovider
      providerId:
        type: string
        description: >
          This cluster's Oneprovider Id. `null` if the Oneprovider is not registered
          or Oneprovider worker is down.
      providerName:
        type: string
        description: >
          The name of this Oneprovider. If the cluster is not configured or
          malfunctioning (e.g. the op-worker service is down), the value may be `null`.
      providerDomain:
        type: string
        description: >
          The domain of this Oneprovider. If the cluster is not configured or
          malfunctioning (e.g. the op-worker service is down), the value may be `null`.
      zoneDomain:
        type: string
        description: >
          The domain of the Onezone where this Oneprovider is registered.
          `null` if the Oneprovider is not registered.
      isRegistered:
        type: boolean
        description: >
          True if the Oneprovider has been registered at a Onezone.
    required:
      - serviceType
      - providerId
      - providerName
      - providerDomain
      - zoneDomain
example:
  serviceType: oneprovider
  providerName: oneprovider-name
  providerDomain: provider.onedata.org
  providerId: b4ceb5c9ac793e6b8b36c813b9068757
  zoneDomain: onedata.org
  build: 155-gdf98e0f
  version: 21.02.0-alpha24
  deployed: true
  isRegistered: true
