type: object
description: The panel configuration.
properties:
  interactiveDeployment:
    type: boolean
    default: true
    description: >
      Indicates that interactive deployment is being performed.

      If false, users entering GUI will not be asked to complete the configuration.
      In that case default values will be used, available for change later
      via appropriate Onepanel GUI pages or REST.
