type: object
description: The provider deployment configuration.
properties:
  cluster:
    $ref: '#/definitions/ProviderClusterConfiguration'
  ceph:
    $ref: '#/definitions/CephCluster'
  oneprovider:
    type: object
    description: The provider custom configuration.
    properties:
      register:
        type: boolean
        description: Defines whether the provider should be registered in a zone.
      token:
        type: string
        description: >
          Registration token obtained from Onezone. This token identifies
          Onezone to be used and authorizes the registration request.
      name:
        type: string
        description: The name under which the provider will be registered in a zone.
      subdomainDelegation:
        type: boolean
        description: >
          If enabled, the storage provider will be assigned a subdomain in onezone's
          domain and 'subdomain' property must be provided. If disabled,
          'domain' property should be provided.
        default: false
      subdomain:
        type: string
        description: >
          Unique subdomain in onezone's domain for the provider. Required if subdomain
          delegation is enabled.
      letsEncryptEnabled:
        type: boolean
        default: false
        description: >
          If enabled the provider will use Let's Encrypt service to obtain SSL certificates.
          Otherwise certificates must be manually provided.
          This option cannot be enabled if subdomainDelegation is false.
          By enabling this option you agree to the Let's Encrypt Subscriber Agreement.
      domain:
        type: string
        description: >
          The fully qualified domain name of the provider or its IP address (only for
          single-node deployments or clusters with a reverse proxy). Required if subdomain
          delegation is disabled.
      geoLongitude:
        type: number
        format: float
        description: The geographical longitude of the provider.
      geoLatitude:
        type: number
        format: float
        description: The geographical latitude of the provider.
      adminEmail:
        type: string
        description: Email address of the oneprovider administrator.
    required:
      - register
      - name
      - adminEmail
  onepanel:
    $ref: '#/definitions/PanelConfiguration'
required:
  - cluster
example:
  cluster:
    domainName: "oneprovider.onedata.example.com"
    nodes:
      node1:
        hostname: "node1"
    manager:
      mainNode: "node1"
      nodes:
        - "node1"
    worker:
      nodes:
        - "node1"
    database:
      nodes:
        - "node1"
    storage:
      NFS:
        type: "posix"
        mountPoint: "/volumes/storage"
  oneprovider:
    register: true
    token: "bWFjYXJvb25mcm9tb25lem9uZQo="
    name: "example"
    subdomainDelegation: false,
    letsEncryptEnabled: false,
    domain: "provider.example.com"
    adminEmail: "admin@example.eu"
    geoLongitude: -24.3776025
    geoLatitude: -128.3519364
