type: object
description: The provider deployment configuration.
properties:
  cluster:
    $ref: '#/definitions/ClusterConfigurationDetails'
  oneprovider:
    type: object
    description: The provider custom configuration.
    properties:
      name:
        description: The name of a provider. Null if not registered.
        type: string
      configured:
        description: True if all steps of cluster deployment and configuration have been performed.
        type: boolean
    required:
      - name
      - configured
required:
  - cluster
  - oneprovider
example:
  cluster:
    master: "node1.oneprovider.onedata.example.com"
    manager:
      mainHost: "node1.oneprovider.onedata.example.com"
      hosts:
        - "node1.oneprovider.onedata.example.com"
    worker:
      hosts:
        - "node1.oneprovider.onedata.example.com"
    database:
      hosts:
        - "node1.oneprovider.onedata.example.com"
  oneprovider:
    name: "example"
    configured: true
