type: object
description: Configuration of files-popularity mechanism in the space.
properties:
  enabled:
    type: boolean
    description: If true, collecting files-popularity mechanism in the space is enabled
  restUrl:
    type: string
    description: >
      REST endpoint to view files-popularity statistics
  lastOpenHourWeight:
    type: number
    description: >
      Weight of `lastOpenHour` parameter.
    default:  1.0
  avgOpenCountPerDayWeight:
    type: number
    description: >
      Weight of `avgOpenCountPerDayWeight` parameter.
    default:  0.75
required:
  - enabled
  - lastOpenHourWeight
  - avgOpenCountPerDayWeight
example:
  enabled: true
  restUrl: https://example.com/api/v3/oneprovider/spaces/example_space_id/indexes/files-popularity?spatial=true&start_range=\[1,0,0,0,0,0\]&end_range=\[null,null,null,null,null,null\]
  lastOpenHourWeight: 1.0
  avgOpenCountPerDayWeight: 0.75