type: object
description: Configuration of files-popularity mechanism in the space.
properties:
  enabled:
    type: boolean
    description: If true, collecting files-popularity mechanism in the space is enabled
  exampleQuery:
    type: string
    description: >
      Example `curl` command that can be executed to query the files-popularity view in the space.
  lastOpenHourWeight:
    type: number
    format: float
    description: >
      Weight of `lastOpenHour` parameter.
    default:  1.0
  avgOpenCountPerDayWeight:
    type: number
    format: float
    description: >
      Weight of `avgOpenCountPerDayWeight` parameter.
    default:  25.0
  maxAvgOpenCountPerDay:
    type: number
    format: float
    description: >
      Maximal value of average open count per day taken to calculate the value of popularity function.
    default:  100
required:
  - enabled
example:
  enabled: true
  restUrl: "curl -sS --tlsv1.2 -k -H 'X-Auth-Token: $TOKEN' -X GET https://$HOST/api/v3/oneprovider/spaces/example_space_id/indexes/files-popularity?limit=10&stale=false"
  lastOpenHourWeight: 1.0
  avgOpenCountPerDayWeight: 25.0
  maxAvgOpenCountPerDay:  100