type: object
description: >
  Configuration of the storage import mechanism.
properties:
  mode:
    description: >
      Mode of the storage import mechanism.

      In case of `auto` mode, the storage will be automatically
      scanned and data will be imported from storage into the assigned Onedata space without need for copying the data.
      It is possible to enable periodical scans for automatic detection of changes on the storage
      (look at option `continousScan`).

      In case of `manual` mode, the files must be registered manually by calling REST API.
      For more info please read: https://onedata.org/#/home/api/stable/oneprovider?anchor=tag/File-registration

    type: string
    enum: [auto, manual]
    default: auto
    x-onedata-default-value: '<<"auto">>'
  continuousScan:
    description: >
      This option is relevant only if mode is set to `auto`.
      With this option enabled the storage will be scanned periodically and direct changes on the
      storage will be reflected in the assigned Onedata space (upon the consecutive scan).
    type: boolean
    default: false
  scanConfig:
    $ref: '#/definitions/AutoStorageImportScanConfig'
