type: object
description: The Onezone deployment configuration.
properties:
  cluster:
    $ref: '#/definitions/ZoneClusterConfiguration'
  onezone:
    type: object
    description: The Onezone custom configuration.
    properties:
      domainName:
        description: The domain of Onezone cluster.
        type: string
      name:
        description: The Onezone cluster name.
        type: string
      letsEncryptEnabled:
        type: boolean
        default: false
        description: >
          If enabled the zone will use Let's Encrypt service to obtain SSL certificates.
          Otherwise certificates must be manually provided.

          By enabling this option you agree to the Let's Encrypt Subscriber Agreement.
      builtInDnsServer:
        type: boolean
        description: >
          If true, DNS check will verify that control of DNS zone for Onezone's
          domain was delegated to the DNS server built into Onezone service.
      policies:
        $ref: '#/definitions/ZonePolicies'
      users:
        type: array
        description: List of Onezone user specifications.
        x-onedata-default-value: "[]"
        default: []
        items:
          $ref: '#/definitions/OnezoneUserCreateRequest'
  onepanel:
    $ref: '#/definitions/PanelConfiguration'
required:
  - cluster
example:
  cluster:
    domainName: "onezone.onedata.example.com"
    nodes:
      node1:
        hostname: "node1"
    manager:
      mainNode: "node1"
      nodes:
        - "node1"
    worker:
      nodes:
        - "node1"
    database:
      nodes:
        - "node1"
  onezone:
    domainName: "example.com"
    name: "example"
    letsEncryptEnabled: true
    users:
      - username: "ozadmin"
        password: "somepassword"
        groups: ["admins"]

