get:
  operationId: get_zone_configuration
  summary: Get zone cluster configuration
  description: Returns the zone cluster configuration.
  x-onedata-gri:
    type: onp_zone
    aspect: cluster
  tags:
    - Onezone Cluster
  produces:
    - application/json
  responses:
    '200':
      description: The zone cluster configuration.
      schema:
        $ref: '#/definitions/ZoneConfigurationDetails'
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '409':
      description: Cluster already deployed.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  x-code-samples:
  - lang: Shell
    source: onepanel-rest-cli -u onepanel:$PASSPHRASE getZoneConfiguration --host https://$OZ_PANEL_HOST:9443


post:
  operationId: configure_zone
  summary: Configure zone deployment
  description: >
    Configures and starts zone services, such as database, cluster manager
    and cluster worker.

    This request can be executed by unauthorized users as long as there are no
    admin users in the system.
  x-onedata-gri:
    type: onp_zone
    aspect: cluster
  tags:
    - Onezone Cluster
  consumes:
    - application/json
    - application/x-yaml
  responses:
    '202':
      $ref: '#/responses/TaskStarted'
    '400':
      description: Invalid request - cluster already deployed.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: zoneConfiguration
    in: body
    description: The zone configuration description.
    schema:
      $ref: '#/definitions/ZoneConfiguration'
    required: true
  x-code-samples:
  - lang: Shell
    source: cat zone_config.json | onepanel-rest-cli -u onepanel:$PASSPHRASE configureZone --host https://$OZ_PANEL_HOST:9443
