get:
  operationId: get_provider_configuration
  summary: Get provider cluster configuration
  description: Returns the provider cluster configuration.
  x-onedata-gri:
    type: onp_provider
    aspect: cluster
  tags:
    - Oneprovider Cluster
  produces:
    - application/json
  responses:
    '200':
      description: The provider cluster configuration.
      schema:
        $ref: '#/definitions/ProviderConfigurationDetails'
    '401':
      description: Unauthorized request.
    '403':
      description: Forbidden request.
    '404':
      description: Cluster is not fully deployed.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  x-code-samples:
  - lang: Shell
    source: onepanel-rest-cli -u onepanel:$PASSPHRASE getProviderConfiguration --host https://$HOST:9443

post:
  operationId: configure_provider
  summary: Configure provider deployment
  description: >
    Configures and starts provider services, such as database, cluster manager
    and cluster worker. Depending on the configuration, sets up provider storage
    and registers in the zone.

    This request can be executed unauthorized as long as there are no admin users.
  x-onedata-gri:
    type: onp_provider
    aspect: cluster
  tags:
    - Oneprovider Cluster
  consumes:
    - application/json
    - application/x-yaml
  responses:
    '202':
      $ref: '#/responses/TaskStarted'
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '409':
      description: Cluster already deployed.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: providerConfiguration
    in: body
    description: The provider configuration description.
    schema:
      $ref: '#/definitions/ProviderConfiguration'
    required: true
  x-code-samples:
  - lang: Shell
    source: cat provider_config.json | onepanel-rest-cli -u onepanel:$PASSPHRASE configureProvider --host https://$HOST:9443 -
